[caddy-core]
fetch.github = "caddyserver/caddy"
src.github = "caddyserver/caddy"
# pinned = true  # pin golang version
[caddy-plugin-cloudflare]
fetch.github = "caddy-dns/cloudflare"
src.git = "https://github.com/caddy-dns/cloudflare.git"
src.branch = "master"
# pinned = true  # pin golang version
[hass-sgcc]
fetch.github = "ARC-MX/sgcc_electricity_new"
src.github = "ARC-MX/sgcc_electricity_new"
[kubecolor-catppuccin]
fetch.github = "vkhitrin/kubecolor-catppuccin"
src.git = "https://github.com/vkhitrin/kubecolor-catppuccin.git"
src.branch = "main"
[kubectl-switch]
fetch.github = "mirceanton/kubectl-switch"
src.github = "mirceanton/kubectl-switch"
[rime-moqi-yinxing]
fetch.github = "gaboolic/rime-shuangpin-fuzhuma"
src.git = "https://github.com/gaboolic/rime-shuangpin-fuzhuma.git"
src.branch = "main"
[talosctl]
fetch.github = "siderolabs/talos"
src.github = "siderolabs/talos"
[talos-api]
fetch.github = "siderolabs/discovery-service"
src.github = "siderolabs/discovery-service"
[zotregistry]
fetch.github = "project-zot/zot"
src.github = "project-zot/zot"
[zotregistry-ui]
fetch.github = "project-zot/zui"
src.git = "https://github.com/project-zot/zui.git"
src.branch = "main"
