[geo-custom]
fetch.github = "soulwhisper/geo"
src.git = "https://github.com/soulwhisper/geo.git"
src.branch = "main"
[mosdns-custom]
fetch.github = "yyysuo/mosdns"
src.git = "https://github.com/yyysuo/mosdns.git"
src.branch = "main"
[singbox-custom]
fetch.github = "CHIZI-0618/sing-box"
src.git = "https://github.com/CHIZI-0618/sing-box.git"
src.branch = "dev-next"
